# Generated by Django 4.2 on 2023-05-09 14:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customers", "0002_customer_credit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="credit",
            field=models.FloatField(null=True),
        ),
    ]
