# Generated by Django 5.2.5 on 2025-10-26 12:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(db_default=datetime.datetime(2025, 10, 26, 12, 47, 30, 190965)),
        ),
    ]
