# Generated by Django 4.2 on 2023-05-15 11:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0002_alter_orderposition_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="total_price",
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
